//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderId { get; set; }
        public Nullable<int> OrderPrice { get; set; }
        public Nullable<bool> isCheckout { get; set; }
        public string Id { get; set; }
        public Nullable<int> totalAmount { get; set; }
        public Nullable<System.DateTime> orderDate { get; set; }
        public string Address_one { get; set; }
        public string Address_two { get; set; }
        public string email { get; set; }
        public Nullable<int> phoneNumber { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Payment_Method { get; set; }
        public string City { get; set; }
        public string User_id { get; set; }
        public string Messege { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
