//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpetialOrder
    {
        public int OrderId { get; set; }
        public string Type { get; set; }
        public string Comment { get; set; }
        public string Image { get; set; }
        public string Message { get; set; }
        public Nullable<int> Status { get; set; }
        public string Address { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> CategoryId { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
